export default [
  {
    id: 1,
    postedOn: "2023-10-28",
    title: "ios Developer",
    company: "Apple",
    type: "Full Time",
    experience: "Mid Level",
    location: "Remote",
    skills: ["SwiftUI", "UIKit", "Core Data"],
    job_link: "https://jobs.apple.com/en-in/search?location=india-INDC&page=2",
  },
  {
    id: 2,
    postedOn: "2023-10-30",
    title: "Frontend Developer",
    company: "Google",
    type: "Full Time",
    experience: "Entry Level",
    location: "Bangalore, India",
    skills: ["HTML", "CSS", "JavaScript", "React"],
    job_link: "https://careers.google.com/jobs/results/123456789/",
  },
  {
    id: 3,
    postedOn: "2023-10-31",
    title: "Backend Developer",
    company: "Amazon",
    type: "Full Time",
    experience: "Senior Level",
    location: "Hyderabad, India",
    skills: ["Node.js", "Express", "MongoDB", "AWS"],
    job_link: "https://www.amazon.jobs/en/jobs/987654321/",
  },
  {
    id: 4,
    postedOn: "2023-11-02",
    title: "Data Scientist",
    company: "Meta",
    type: "Contract",
    experience: "Mid Level",
    location: "Remote",
    skills: ["Python", "Machine Learning", "Pandas", "TensorFlow"],
    job_link: "https://www.metacareers.com/jobs/456789012/",
  },
  {
    id: 5,
    postedOn: "2023-11-04",
    title: "Full Stack Developer",
    company: "Microsoft",
    type: "Part Time",
    experience: "Entry Level",
    location: "Noida, India",
    skills: ["C#", ".NET", "Azure", "SQL Server"],
    job_link: "https://careers.microsoft.com/us/en/job/3456789012/",
  },
  {
    id: 6,
    postedOn: "2023-11-05",
    title: "Cloud Solutions Architect",
    company: "IBM",
    type: "Full Time",
    experience: "Senior Level",
    location: "Pune, India",
    skills: ["AWS", "Azure", "Docker", "Kubernetes"],
    job_link: "https://www.ibm.com/employment/jobid/6543210987/",
  },
];
